apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mongodb
        image: bitnami/mongodb:${DB_IMAGE_TAG}
        ports:
        - containerPort: 27017
        env:
        - name: MONGODB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongodb-root-password
        - name: MONGODB_DATABASE
          value: ${DB_NAME}
        - name: MONGODB_USERNAME
          value: ${DB_USER}
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongodb-password
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: db-pvc
